// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package multipass

import (
	"context"
	"reflect"

	"github.com/incsteps/pulumi-provider-multipass/sdk/go/multipass/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// Path to the multipass binary. Defaults to 'multipass' in PATH.
	MultipassBin pulumi.StringPtrOutput `pulumi:"multipassBin"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.LaunchTimeout == nil {
		args.LaunchTimeout = pulumi.IntPtr(300)
	}
	if args.MultipassBin == nil {
		args.MultipassBin = pulumi.StringPtr("")
	}
	if args.OperationTimeout == nil {
		args.OperationTimeout = pulumi.IntPtr(60)
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:multipass", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Seconds to wait for an instance to become Running. Default 300.
	LaunchTimeout *int `pulumi:"launchTimeout"`
	// Path to the multipass binary. Defaults to 'multipass' in PATH.
	MultipassBin *string `pulumi:"multipassBin"`
	// Seconds to wait for general CLI operations. Default 60.
	OperationTimeout *int `pulumi:"operationTimeout"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Seconds to wait for an instance to become Running. Default 300.
	LaunchTimeout pulumi.IntPtrInput
	// Path to the multipass binary. Defaults to 'multipass' in PATH.
	MultipassBin pulumi.StringPtrInput
	// Seconds to wait for general CLI operations. Default 60.
	OperationTimeout pulumi.IntPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Path to the multipass binary. Defaults to 'multipass' in PATH.
func (o ProviderOutput) MultipassBin() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MultipassBin }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
