// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/incsteps/pulumi-provider-multipass/sdk/go/multipass/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Seconds to wait for an instance to become Running. Default 300.
func GetLaunchTimeout(ctx *pulumi.Context) int {
	v, err := config.TryInt(ctx, "multipass:launchTimeout")
	if err == nil {
		return v
	}
	var value int
	value = 300
	return value
}

// Path to the multipass binary. Defaults to 'multipass' in PATH.
func GetMultipassBin(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "multipass:multipassBin")
	if err == nil {
		return v
	}
	var value string
	value = ""
	return value
}

// Seconds to wait for general CLI operations. Default 60.
func GetOperationTimeout(ctx *pulumi.Context) int {
	v, err := config.TryInt(ctx, "multipass:operationTimeout")
	if err == nil {
		return v
	}
	var value int
	value = 60
	return value
}
