// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { RestoreArgs, RestoreResult, RestoreOutputArgs } from "./restore";
export const restore: typeof import("./restore").restore = null as any;
export const restoreOutput: typeof import("./restore").restoreOutput = null as any;
utilities.lazyLoad(exports, ["restore","restoreOutput"], () => require("./restore"));

