// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function restore(args: RestoreArgs, opts?: pulumi.InvokeOptions): Promise<RestoreResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("multipass:functions:restore", {
        "destructiveRestore": args.destructiveRestore,
        "instanceName": args.instanceName,
        "snapshotName": args.snapshotName,
    }, opts);
}

export interface RestoreArgs {
    destructiveRestore?: boolean;
    instanceName: string;
    snapshotName: string;
}

export interface RestoreResult {
    readonly status: string;
}
export function restoreOutput(args: RestoreOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<RestoreResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("multipass:functions:restore", {
        "destructiveRestore": args.destructiveRestore,
        "instanceName": args.instanceName,
        "snapshotName": args.snapshotName,
    }, opts);
}

export interface RestoreOutputArgs {
    destructiveRestore?: pulumi.Input<boolean>;
    instanceName: pulumi.Input<string>;
    snapshotName: pulumi.Input<string>;
}
