// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package functions

import (
	"context"
	"reflect"

	"github.com/incsteps/pulumi-provider-multipass/sdk/go/multipass/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func Restore(ctx *pulumi.Context, args *RestoreArgs, opts ...pulumi.InvokeOption) (*RestoreResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv RestoreResult
	err := ctx.Invoke("multipass:functions:restore", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type RestoreArgs struct {
	DestructiveRestore *bool  `pulumi:"destructiveRestore"`
	InstanceName       string `pulumi:"instanceName"`
	SnapshotName       string `pulumi:"snapshotName"`
}

type RestoreResult struct {
	Status string `pulumi:"status"`
}

func RestoreOutput(ctx *pulumi.Context, args RestoreOutputArgs, opts ...pulumi.InvokeOption) RestoreResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (RestoreResultOutput, error) {
			args := v.(RestoreArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("multipass:functions:restore", args, RestoreResultOutput{}, options).(RestoreResultOutput), nil
		}).(RestoreResultOutput)
}

type RestoreOutputArgs struct {
	DestructiveRestore pulumi.BoolPtrInput `pulumi:"destructiveRestore"`
	InstanceName       pulumi.StringInput  `pulumi:"instanceName"`
	SnapshotName       pulumi.StringInput  `pulumi:"snapshotName"`
}

func (RestoreOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RestoreArgs)(nil)).Elem()
}

type RestoreResultOutput struct{ *pulumi.OutputState }

func (RestoreResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RestoreResult)(nil)).Elem()
}

func (o RestoreResultOutput) ToRestoreResultOutput() RestoreResultOutput {
	return o
}

func (o RestoreResultOutput) ToRestoreResultOutputWithContext(ctx context.Context) RestoreResultOutput {
	return o
}

func (o RestoreResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v RestoreResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(RestoreResultOutput{})
}
