// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("multipass");

/**
 * Seconds to wait for an instance to become Running. Default 300.
 */
export declare const launchTimeout: number;
Object.defineProperty(exports, "launchTimeout", {
    get() {
        return __config.getObject<number>("launchTimeout") ?? 300;
    },
    enumerable: true,
});

/**
 * Path to the multipass binary. Defaults to 'multipass' in PATH.
 */
export declare const multipassBin: string;
Object.defineProperty(exports, "multipassBin", {
    get() {
        return __config.get("multipassBin") ?? "";
    },
    enumerable: true,
});

/**
 * Seconds to wait for general CLI operations. Default 60.
 */
export declare const operationTimeout: number;
Object.defineProperty(exports, "operationTimeout", {
    get() {
        return __config.getObject<number>("operationTimeout") ?? 60;
    },
    enumerable: true,
});

