// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A Multipass virtual machine instance.
 */
export class Instance extends pulumi.CustomResource {
    /**
     * Get an existing Instance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Instance {
        return new Instance(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'multipass:resources:Instance';

    /**
     * Returns true if the given object is an instance of Instance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Instance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Instance.__pulumiType;
    }

    declare public /*out*/ readonly allIpv4: pulumi.Output<string[]>;
    /**
     * Path to a cloud-init user-data file or inline cloud-init configuration.
     */
    declare public readonly cloudinit: pulumi.Output<string | undefined>;
    /**
     * The number of CPUs to allocate to the instance. Defaults to 1.
     */
    declare public readonly cpus: pulumi.Output<number>;
    /**
     * The disk size to allocate (e.g., '5G', '10G'). Defaults to '5G'.
     */
    declare public readonly disk: pulumi.Output<string>;
    /**
     * The OS image to launch (e.g., '24.04', 'daily:24.04'). Defaults to '24.04'.
     */
    declare public readonly image: pulumi.Output<string>;
    declare public /*out*/ readonly imageHash: pulumi.Output<string>;
    declare public /*out*/ readonly imageRelease: pulumi.Output<string>;
    declare public /*out*/ readonly ipv4: pulumi.Output<string>;
    /**
     * The amount of RAM to allocate (e.g., '1G', '2048M'). Defaults to '1G'.
     */
    declare public readonly memory: pulumi.Output<string>;
    /**
     * The unique name of the Multipass virtual machine instance.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly state: pulumi.Output<string>;

    /**
     * Create a Instance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InstanceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["cloudinit"] = args?.cloudinit;
            resourceInputs["cpus"] = (args?.cpus) ?? 1;
            resourceInputs["disk"] = (args?.disk) ?? "5G";
            resourceInputs["image"] = (args?.image) ?? "24.04";
            resourceInputs["memory"] = (args?.memory) ?? "1G";
            resourceInputs["name"] = args?.name;
            resourceInputs["allIpv4"] = undefined /*out*/;
            resourceInputs["imageHash"] = undefined /*out*/;
            resourceInputs["imageRelease"] = undefined /*out*/;
            resourceInputs["ipv4"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        } else {
            resourceInputs["allIpv4"] = undefined /*out*/;
            resourceInputs["cloudinit"] = undefined /*out*/;
            resourceInputs["cpus"] = undefined /*out*/;
            resourceInputs["disk"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["imageHash"] = undefined /*out*/;
            resourceInputs["imageRelease"] = undefined /*out*/;
            resourceInputs["ipv4"] = undefined /*out*/;
            resourceInputs["memory"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Instance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Instance resource.
 */
export interface InstanceArgs {
    /**
     * Path to a cloud-init user-data file or inline cloud-init configuration.
     */
    cloudinit?: pulumi.Input<string | undefined>;
    /**
     * The number of CPUs to allocate to the instance. Defaults to 1.
     */
    cpus?: pulumi.Input<number | undefined>;
    /**
     * The disk size to allocate (e.g., '5G', '10G'). Defaults to '5G'.
     */
    disk?: pulumi.Input<string | undefined>;
    /**
     * The OS image to launch (e.g., '24.04', 'daily:24.04'). Defaults to '24.04'.
     */
    image?: pulumi.Input<string | undefined>;
    /**
     * The amount of RAM to allocate (e.g., '1G', '2048M'). Defaults to '1G'.
     */
    memory?: pulumi.Input<string | undefined>;
    /**
     * The unique name of the Multipass virtual machine instance.
     */
    name: pulumi.Input<string>;
}
