// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A host directory mount into a Multipass virtual machine instance.
 */
export class Mount extends pulumi.CustomResource {
    /**
     * Get an existing Mount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Mount {
        return new Mount(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'multipass:resources:Mount';

    /**
     * Returns true if the given object is an instance of Mount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Mount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Mount.__pulumiType;
    }

    declare public readonly instanceName: pulumi.Output<string>;
    declare public readonly mountType: pulumi.Output<string | undefined>;
    declare public readonly sourcePath: pulumi.Output<string>;
    declare public readonly targetPath: pulumi.Output<string>;

    /**
     * Create a Mount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MountArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.instanceName === undefined && !opts.urn) {
                throw new Error("Missing required property 'instanceName'");
            }
            if (args?.sourcePath === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourcePath'");
            }
            if (args?.targetPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetPath'");
            }
            resourceInputs["instanceName"] = args?.instanceName;
            resourceInputs["mountType"] = (args?.mountType) ?? "native";
            resourceInputs["sourcePath"] = args?.sourcePath;
            resourceInputs["targetPath"] = args?.targetPath;
        } else {
            resourceInputs["instanceName"] = undefined /*out*/;
            resourceInputs["mountType"] = undefined /*out*/;
            resourceInputs["sourcePath"] = undefined /*out*/;
            resourceInputs["targetPath"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Mount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Mount resource.
 */
export interface MountArgs {
    instanceName: pulumi.Input<string>;
    mountType?: pulumi.Input<string>;
    sourcePath: pulumi.Input<string>;
    targetPath: pulumi.Input<string>;
}
