// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'multipass';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Path to the multipass binary. Defaults to 'multipass' in PATH.
     */
    declare public readonly multipassBin: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["launchTimeout"] = pulumi.output((args?.launchTimeout) ?? 300).apply(JSON.stringify);
            resourceInputs["multipassBin"] = (args?.multipassBin) ?? "";
            resourceInputs["operationTimeout"] = pulumi.output((args?.operationTimeout) ?? 60).apply(JSON.stringify);
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Seconds to wait for an instance to become Running. Default 300.
     */
    launchTimeout?: pulumi.Input<number>;
    /**
     * Path to the multipass binary. Defaults to 'multipass' in PATH.
     */
    multipassBin?: pulumi.Input<string>;
    /**
     * Seconds to wait for general CLI operations. Default 60.
     */
    operationTimeout?: pulumi.Input<number>;
}
